services:
  db:
    image: postgres:15-alpine
    container_name: realestate_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sifreniz
      - POSTGRES_DB=RealEstateDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: